"""empty message

Revision ID: 2e7deb66b4de
Revises: d2f222aafa4e
Create Date: 2017-07-21 01:36:54.636854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7deb66b4de'
down_revision = 'd2f222aafa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dalsi_sloupec', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dalsi_sloupec')
    # ### end Alembic commands ###
